### ISSUE TITLE
Question: "latest contribution"

### ISSUE THREAD

**Issue by bhilburn** [licensezero/parity-public-license#12]
IANAL.

The parity license currently includes this text:

```
If you follow the rules below, you may do everything with
this software that would otherwise infringe my copyright in
it or any patent claim I can license that you would infringe
by using this software as of my latest contribution.
```

My question pertains to the last words, there, `as of my latest contribution`. Upon first reading, I was surprised it didn't instead refer to the version of the software received with this license.

If, for example, I make several releases of a project under Parity, and then change the license to something else, it seems to me that the wording could be interpreted to mean this phrase applies to the later versions - even though the license has been changed.

Is that a plausible concern?

**Comment by kemitchell** [comment]
@bhilburn, thanks for this issue!

When talking about rules like this, we should keep in mind that there are unavoidably a few sets of rules we might be talking about at any given time:

<dl>
<dt>Designed Terms</dt><dd>The rules I had in mind, and wanted to implement in the license.</dd>
<dt>Implemented Terms</dt><dd>The rules I actually wrote, within the constraints I chose for the license text.</dd>
<dt>Applied Terms</dt><dd>The rules that parties discussing a settlement, or a court applying the license, would apply. A subject of speculation.</dd>
</dl>

Obviously, we write and use licenses for _Applied Terms_, for effect. In the end, the _Applied Terms_ get determined by the _Implemented Terms_, not _Designed Terms_. But I'd like to say things about my _Designed Terms_, and then move on to how I made them _Implemented Rules_, before speculating about how it would play out in practice.

## Patent Design Goals

The License Zero family of licenses---Parity, Prosperity, Charity---all share two related and potentially conflicting goals:

1. Give users clear patent licenses.
2. Give contributors complete control over which of their patents get licensed.

### Test Case

Consider a Parity package development timeline like so:

- A contributes the initial work. On their own, A's contributions don't infringe any patents.
- B contributes an optimization. With B's optimization, the combined A∪B codebase now infringes a patent claim.
- A acquires the patent.

Does A's Parity license now cover the patent? That would violate patent rule 2. B's actions---adding code that brings the package under the patent---would control which patents A licenses. Let's look at the text:

> any patent claim I can license

True. A acquired the patent, and can license it.

> that you would infringe by using this software

True. The combination of A's contributions and B's contributions infringes the patent.

> as of my latest contribution.

_False_.  A's latest contribution came _before_ B added the optimization, and brought the package within the patent claim.

Result: A does _not_ license the patent.

### Variation

Continue with our running example. A comes back to the project, and adds work building on top of B's optimization, say to add a runtime flag to toggle the optimization. Now we have three contributions:

1. A contributes initial work.
2. B contributes the optimization.
3. A contributes the runtime flag.

> any patent claim I can license

True. A acquired the patent, and can license it.

> that you would infringe by using this software

True. The combination of A's contributions and B's contributions infringes the patent.

> as of my latest contribution.

True.  A's latest contribution came _after_ and _on top of_ B's optimization.

Result: A _does_ license the patent.

A didn't contribute the code that brings the combined package within the patent claim. B did. But A decides whether or not to contribute to the package again, and whether to do so atop B's contributions, or to continue their own line of development, creating a fork.

The intended upshot here is that each contributor can do their own patent analysis every time they go to contribute. If they think contributing would trigger licensing a patent they don't want to license, they can choose not to contribute, or to fork, to avoid building on the contributions that bring the package within the patent claim. No _other_ contributor can force them to license any patent.

## "This Software"

You wrote:

> If, for example, I make several releases of a project under Parity, and then change the license to something else, it seems to me that that wording could be interpreted to mean that this wording applies to the later versions - even though the license has been changed.

Good test case!

Recall patent goal number 2: "Give contributors complete control over which of their patents get licensed.". It is _not_ an intended goal of the License Zero licenses to require licensing of patents in later versions of a formerly Parity-licensed project, after it gets relicensed.

Now we have to talk about the _Implemented Rules_. Every license needs language to refer to _the stuff being licensed_. For copyright licenses, that _stuff_ is pretty concrete: copyright in the written source code to which copyright applies. For patents, it's different. The _stuff_ is a patent claim, a legal right, that isn't so directly attached to the written source code. Oftentimes, technical folks find it helps to think about copyright in terms of string equality and patent in terms of a regular expression. Copyright applies to particular work: if source code is identical, or nearly identical, to parts of copyrighted code without permission, the copyright is infringed. But if source code implements the pattern described by a patent claim, the source code infringes the patent, no matter how the particular source code was written.

The License Zero family of licenses, including Parity, all use "this software" to define the _stuff_ being licensed. What copyrights are being licensed?

> ... you may do everything with this software that would otherwise infringe my copyright in it [this software] ...

Now we can talk about _Applied Terms_. In my opinion, "this software" in Parity will refer to the particular source code that comes along with the license, and not any future (or different) version of the same project that may appear later, with different license terms. To read it otherwise would mean that Parity gives a copyright license for code that potentially does not exist yet, or for source code that gets added to the same "project" by other contributors who don't have the legal right to license it. In other words, I think Parity gives a copyright license for just the copyrights in the particular source code that comes with the copy of the Parity license terms.

Now let's look at the patent language:

>  or any patent claim I can license that you would infringe by using this software as of my latest contribution

Note that the copyright language and the patent language _share "this software" in common_. If Parity were a program, we might imagine `thisSoftware()` as a helper function that both `copyright()` and `patent()` call.

If "this software" really only makes sense in the copyright context if it refers to the specific source code that comes along with the license, then I think "this software" means only that specific version for the patent language, too.

In your example, we might imagine coming across two copies of different versions of the project:

- Version 1.0.0, originally licensed, with Parity in `LICENSE`.
- Version 2.0.0, relicensed, with some other terms in `LICENSE`.

Let's say 2.0.0 infringes a patent owned by the author, but 1.0.0 does not.

For the reasons above, I would "this software" in the Parity license for 1.0.0 to refer only to that copy of the 1.0.0 source code. I would _not_ read it to refer to 2.0.0, as well. So the part of the Parity license for 1.0.0 that says "you may do everything with this software..." _not_ cover things you do with 2.0.0, or cover patents that 2.0.0 infringes.

---

Some of it's due to list formatting, but I do regret the length of this response. Thank you for reading. Your questions was deep and also fairly specific. I hope I was able to give a clear answer, clear reasons, and a sense of context.

**Comment by bhilburn** [comment]
Thanks for the thorough explanation - much appreciated! Based on your description, I now understand how you are distinguishing between patent licenses granted by a contributor as of their most recent contribution in the code (as it exists in the form received by the licensee), and whatever may have happened in software commit history since then.

That does indeed make sense, and I appreciate its protection of contributors' IP rights. It is not something I would have understood without guidance from a counsel, but the language makes sense now that you've explained it.

Closing this issue out.

**Comment by kemitchell** [comment]
@bhilburn, thanks for closing. Just writing to add that this conversation inspired a blog post on the "different kinds of terms" concept, which I think will be very useful in other conversations, too:

https://blog.licensezero.com/2018/07/13/talking-about-license-rules.html
