### ISSUE TITLE
Big Thanks to Jeremy Sherman

### ISSUE THREAD

**Issue by kemitchell** [licensezero/parity-public-license#42]
@jeremy-w, I hope you don't me creating an issue just to thank and recognize you. From my point of view, working on this license with you has been one of the most rewarding work experiences of the past year. The License Zero Reciprocal Public License felt like a beating. Parity's a privilege!

I'm really starting to get the feeling that this license isn't "mine" anymore, but "ours', in a broader, more general sense encompassing you and a few other folks who've given such great thought and feedback. Obviously the buck stops with me, as far as the law part of this goes. But this license is far better than I could ever make it alone. Better than a whole conference room of just lawyers could make it.

Thanks!

**Comment by makkus** [comment]
I totally agree, except that I think the license was already pretty great before anybody else chipped in. So please keep a big chunk of the credit to yourself @kemitchell ! 
Reading peoples thoughtful comments about the meaning and placement of just one or two words is great. Honestly, this is my favourite 'issue-stream' I'm subscribed to. I almost wish for more issues to be raised, because it's always interesting. :-)

**Comment by kemitchell** [comment]
@makkus, you better watch yourself. I might just open a sappy issue about you, too!

**Comment by jeremy-w** [comment]
Aww shucks. Thanks! It's been amazing to play a role in the careful thought put into this.
