### ISSUE TITLE
An user suggested wording changes to Parity.

### ISSUE THREAD

**Issue by kori** [licensezero/parity-public-license#50]
Hey! I adopted the Parity Public License in my project, and an user opened an issue suggesting some word changes. As I have not drafted the license, and as I am not a lawyer, I'd like to forward the issue here, to ask for help and to see what considerations you might have.

The issue is: https://github.com/kori/Xlambda/issues/5

The issue is reproduced below:

> Hi. There's currently an open issue to change the license (FWIW I recommend BSD-2); I'll let you deal with that as you wish, but as is I have some recommendations to change the wording of the license. Specifically:
> 
>"This license lets you use and share this software for free, as long as you contribute software you make with it. Specifically"

> - this could be read as saying that this is the only constraint, and the rest of the license is simply clarifying; which isn't true. I might say "...as long as you abide by certain conditions. These are:"

>"If you follow the rules below, you may do everything with this software that would otherwise infringe either the contributor's copyright in it, any patent claim the contributor can license, or both"

>- This part is overly wordy, IMO, and could in theory exclude some activities your users might want to do. I would just say "You may deal in this software without restriction, so long as you abide by the following rules:"

> -All the rules should be in the second person, so e.g. 'you must contribute changes and additions...' instead of just 'contribute changes and additions'.

>Put definitions before everything else, so they can't accidentally be mistaken for terms. That is, put a section right after the copyright line, saying 'definitions: Software: all source and binary files and other associated works of [... whatever]; Source code: preferred form for modifying the software; Contribute: make available..."

>- Make it very clear that you are defining the term 'contribute' to mean what you want it to mean, otherwise it could be twisted.

>The second-to-last line has a number of confusing and ambiguous sections. 'unknowingly breaking 1, 2, or 3' should be 'unknowingly breaking rules 1, 2, or 3'. Also take out unknowingly; it's very hard, legally, to prove knowledge. Similarly, at the end you should say 'within 30 days of being informed you broke the license terms'. Also 'stop doing anything requiring this license' is really vague; you don't need a license to do anything! I'm honestly not sure what you meant by that; maybe just take it out entirely?

>And by the way, this is the reason you should really just switch to a standard license like BSD or Apache. I'm not a lawyer, and I already found a list of problems longer than the license itself :P
> 
>Oh, also, you need to pluralise everywhere it says 'contributor' because I contributed :)

**Comment by kemitchell** [comment]
None of these criticisms make much sense to me. The author seems to believe that in order to be clear, a license has to read like MIT or BSD, when in fact those old terms are chock full of known problems.

@kori, you should do your own homework, and make your own judgment call, but this seems awfully like FUD from someone who'd rather you adopt a fundamentally different license. Plenty of individuals and companies have made good use of both Parity and Prosperity.

**Comment by kemitchell** [comment]
FWIW, if the author of the comments would like to open issues here, I'll be happy to discuss.

**Comment by kori** [comment]
Alright Kyle, thanks a lot!

I don't seek to move from Parity, and the terms it provides are very desireable to me.

Do you have any suggestions on where I can read more about this? Would just the licensezero website suffice?

**Comment by Elronnd** [comment]
> None of these criticisms make much sense to me. The author seems to believe that in order to be clear, a license has to read like MIT or BSD, when in fact those old terms are chock full of known problems.

Can you address the problems individually?  I do support the development of new licenses, but I think that, in case of doubt, licenses where there exists a precedent for what they mean should be used.  And I don't think that this is the right license to replace them since I, a non-lawyer, was immediately able to spot certain problems.  Am 100% open to being corrected, though.

**Comment by makkus** [comment]
> Can you address the problems individually?

To be perfectly honest, I don't really understand your criticisms either. Mostly you say this and this should be different, but don't really offer an explanation as to why. And if you offer an explanation, I fail to see the relevance. One example:

> All the rules should be in the second person, so e.g. 'you must contribute changes and additions...' instead of just 'contribute changes and additions'.

Why is that? To me, there is no difference in meaning, and the original is more concise and reads better. 

Btw, the author of the license is an actual lawyer, so you should be at least somewhat reassured that there are no really obvious holes in the wording. Also, I'd recommend you check out the [licensezero blog](https://blog.licensezero.com/). Lots of in-depth info on the license(s), and the reasonings behind them...

**Comment by kemitchell** [comment]
There's nothing exclusive about the phrasing of the first paragraph. Courts do not read one paragraph and stop. They will interpret specific words in the context of the license as a whole.

Your BSD-like "without restriction" proposal misses the point of granting explicit, well scoped copyright and patent permission, which is perhaps the best-known and most-important flaw of BSD terms. Lawyers are _still_ fighting about whether MIT and BSD grant patent licenses, and if so, what those licenses cover, and when.

I don't see why the numbered rules have to be in the second person. Feedback from non-legal readers consistently emphasized the clarity of imperative sentences.

I don't understand why you think formal definitions are required, how formal definitions differ from "terms", or how the current approach to "contribute" risks any misunderstanding.

You claim ambiguity in the cure provision's cross-references, but I don't see it. What else would "1, 2, or 3" refer to?

You are right that proof of knowledge is relatively difficult, but knowledge issues in both criminal and civil disputes are very common. Who bears the burden of showing knowledge or lack of knowledge for a breach? Is that in line with the goals of the license?

The phrase "doing anything requiring this license" is made clear by the rest of the license. Without a copyright license, reproducing, distributing to the public, preparing derivative works, and so on can constitute copyright infringement. Without a patent license, making, using, offering, selling, and importing can constitute patent infringement.

**Comment by Elronnd** [comment]
> There's nothing exclusive about the phrasing of the first paragraph. Courts do not read one paragraph and stop. They will interpret specific words in the context of the license as a whole.

Ok.

> Your BSD-like "without restriction" proposal misses the point of granting explicit, well scoped copyright and patent permission, which is perhaps the best-known and most-important flaw of BSD terms. Lawyers are still fighting about whether MIT and BSD grant patent licenses, and if so, what those licenses cover, and when.

Fair enough.  Mostly I object to 'that would otherwise infringe [...]', because it's white-listing rather than black-listing.  That is, there might be certain things, that people would want to do, which wouldn't infringe on copyright or patent rights, but which could still infringe on other rights; the ability for people to do this was never explicitly granted.  So I would say, rather than 'you can do anything that would otherwise infringe...', 'you can do anything, including things that would otherwise infringe...'

> I don't see why the numbered rules have to be in the second person

Mostly because the second rule is in second person; shouldn't they be consistent?

> I don't understand why you think formal definitions are required, how formal definitions differ from "terms", or how the current approach to "contribute" risks any misunderstanding.

I don't necessarily think formal definitions are required.  There is definitely a difference between them and terms, though; terms are something you agree to abide by, definitions are only useful in reducing wordiness of terms.  Where it says 'to contribute software, publish all its source code...', that makes it sound like that's an *example* of a way you could contribute, rather than that that, exclusively, is what is meant by contributing.

> You are right that proof of knowledge is relatively difficult, but knowledge issues in both criminal and civil disputes are very common. Who bears the burden of showing knowledge or lack of knowledge for a breach? Is that in line with the goals of the license?

Oh, I see; this clause is aimed at individuals making individual changes, so they don't have to push to a public git repo every keystroke they make right after they make it; not large corporations accused of breaching the license.  Is that right?

> The phrase "doing anything requiring this license" is made clear by the rest of the license. Without a copyright license, reproducing, distributing to the public, preparing derivative works, and so on can constitute copyright infringement. Without a patent license, making, using, offering, selling, and importing can constitute patent infringement.

Well, let's say the linux kernel were published under this license.  And I'm distributing microwaves that have a modified version of linux, and I don't publish the source code.  How can I follow that?  I can publish the code, or I can 'stop doing anything requiring the license'?  How?  Even if I stop distributing microwaves, I still have those changes and they will continue to exist after 30 days.  Even if I delete the modified code, it still was modified.

**Comment by kemitchell** [comment]
> That is, there might be certain things, that people would want to do, which wouldn't infringe on copyright or patent rights, but which could still infringe on other rights; the ability for people to do this was never explicitly granted.

If those things are copyright "fair use", you don't need a license to do them. If those things might violate other kinds of rights, like trademarks or publicity rights, Parity doesn't mean to license them. Neither do other open software licenses.

Even permissive standards, like Apache 2.0, don't give completely blank checks. You can't infringe trademarks with an Apache-licensed program. You can't use an Apache-licensed security tool to hack the developer's e-mail account.

MIT and BSD are less clear on this point overall. But I don't think they give total impunity, either.

Go to the extreme: Would a court read the WTFPL license for a chat app to permit sending physical threats to the developer? Sending unauthorized copies of the developers' private journal over chat? I don't think so.

> Oh, I see; this clause is aimed at individuals making individual changes, so they don't have to push to a public git repo every keystroke they make right after they make it; not large corporations accused of breaching the license. Is that right?

I don't see how you got to that reading. Parity never uses the term "individual", "corporation", "entity", or similar.

> Well, let's say the linux kernel were published under this license. And I'm distributing microwaves that have a modified version of linux, and I don't publish the source code. How can I follow that?

Let's say the Linux kernel is GPLv2-licensed instead, and that a bunch of developers have signed onto [a public commitment](https://gplcc.github.io/gplcc/) to follow a GPLv3-style cure language, including requirements to "cease all violation of this License" and "cure the violation". What then?
