### ISSUE TITLE
the "dissident test" and "desert island" test

### ISSUE THREAD

**Issue by bradrydzewski** [licensezero/parity-public-license#59]
There was a conversation on Twitter about Parity and the "desert island test" and "dissident test" were referenced. I find the latter interesting given some of the things going on in the world today (protestors in HK using open source software to communicate, etc). I was wondering your thoughts on this?

I hesitate to bring up specifics, but I was genuinely curious about the term "best efforts" which I sometimes see in legal documents. What would a best effort to contribute software look like and could it end up being used as a loophole to weaken copyleft?

**Comment by kemitchell** [comment]
Ah, the Debian corner cases.

But before we go there, where is "best efforts" coming from? One of the corner cases? An idea about how to change Parity to avoid it?

"Best Efforts" is one of those legal crutches, like "reasonable", that has taken on a patina of precision by repeated legal use, rather than offering any actual precision. There is lots of litigation about "best efforts", and also "reasonable efforts", "good faith effort", and a handful of similarly indistinguishable doublets and triplers. Ken Adams in particular has been trying to break lawyers out the habit of them for years:

https://adamsdrafting.com/downloads/Best-Efforts-Practical-Lawyer.pdf

https://www.adamsdrafting.com/what-does-best-efforts-mean/

**Comment by bradrydzewski** [comment]
> But before we go there, where is "best efforts" coming from? One of the corner cases? An idea about how to change Parity to avoid it?

yes, good question, I will walk you through my train of thought 🙂 

1. the comment on twitter got me thinking about the dissident test as it related to Parity
2. the corporation I worked for years ago used "best efforts" in their contracts sometimes
3. this got me wondering if Parity could use similar language to pass the dissident test. what if it required making a "best effort" to contribute? It _feels_ like such a change could support this corner case. Making a best effort to contribute code on a desert island, but failing, would not cause a license violation and therefore pass the test.
    > You are excused for unknowingly breaking Copyleft if you __make a best effort__ to contribute as required"
4. then I wondered if it could be abused.  If an employee asks their boss to contribute code, and the boss threatens to fire the employee if they contribute, has the employee made a best effort?
5. I also figured you probably thought about this already, and I almost deleted the issue
6. finally I decided to ask anyway, because I was just too curious to see your response and I knew I would learn something in the process

the reading you provided was informative and highlights some of the issues with _efforts_

> The case law, however, paints a different picture. Courts have not required that a party under a duty to use best efforts to accomplish a given goal make every conceivable effort to do so, regardless of the detriment to it. 

> The requirement that a party use its best efforts necessarily does not prevent the party from giving reasonable consideration to its own interests

it sounds like courts do acknowledge the phrasing, but it sounds like the ambiguity can be problematic, and could allow companies to circumvent ...

**Comment by kemitchell** [comment]
The Debian Free Software Guidelines and Open Source Definition [remain largely the same](https://writing.kemitchell.com/2017/11/12/DFSG-versus-OSD.html). Neither gives good structure for analyzing a license, for nearly any purpose, other than simply creating as many opportunities to free associate objections as possible. But if one must treat them as holy texts---[ill-advised](https://writing.kemitchell.com/2019/04/23/OSD-wontfix.html)---here's a bit of analysis on criterion 9 in particular, from some time ago:

https://writing.kemitchell.com/2018/11/05/OSD-Copyleft-Regulation.html#contamination

Criticism of rule 3 as "vague" seems shallow, knee-jerk. Breadth isn't vagueness. When the point is exactly breadth, indirect calls to be more specific aren't constructive.

In many ways, Parity exists because GPL fell into the trap of over-specificity. It might be the best example of the reductive programming mindset misapplied to legal drafting to date, in the way that it insists on expressing "share alike" in terms of exclusive rights of copyright holders listed in the copyright law. Courts don't halt and dump core when they reach fuzzy natural language. Fuzzy natural language is all of their input, and all of their output. It's messy natural language all the way down.

By contrast, criticism of rule 3 as "far-reaching" I take as a compliment. That's as intended.

I strongly oppose muddying Parity's entire copyleft rule with "best effort" or "reasonable" or "practical" or the like. Those terms add nothing _but_ vagueness---they have no reliable, broadly understood meaning in law. That's why I call them "crutches". Lawyers use crutches when they lack the conviction of the rules they've written. That is not where Parity is coming from.

**Comment by bradrydzewski** [comment]
> But if one must treat them as holy texts [...]
> Criticism of rule 3 as "vague" seems shallow, knee-jerk [...]

I agree. I was less interested in her comments regarding criteria 9 and rule 3.

I was more interested in the dissident test because it came up, along with security disclosures, as arguments against requiring publishing source in CAL discussions and again on twitter. I do not have much understanding regarding how contributing code would effect dissidents, but thought it was worth getting your opinion.

> I strongly oppose muddying Parity's entire copyleft rule with "best effort" or "reasonable" or "practical" or the like. Those terms add nothing but vagueness---they have no reliable, broadly understood meaning in law. That's why I call them "crutches". Lawyers use crutches when they lack the conviction of the rules they've written. That is not where Parity is coming from.

I understand and agree having read the materials you posted. I can see why someone might want to use "reasonable efforts" in the context of support (perhaps it gives some wiggle room if you miss deadlines or service levels). However, I do understand why you would avoid this language in the copyleft clause. Thanks for taking the time to reply and educate me on the topic!

**Comment by kemitchell** [comment]
The problem with the dissident test is that's not a viable corner case. License terms are enforced, in the end, via state power. If the state is your enemy, you're not going to fret copyright claims, and even if the state chooses to use copyright claims as cover for your persecution, that's just window dressing.

**Comment by kemitchell** [comment]
The problem with the dissident test is that's not a viable corner case. License terms are enforced, in the end, via state power. If the state is your enemy, you're not going to fret copyright claims, and even if the state chooses to use copyright claims as cover for your persecution, that's just window dressing.

**Comment by kemitchell** [comment]
The problem with the dissident test is that's not a viable corner case. License terms are enforced, in the end, via state power. If the state is your enemy, you're not going to fret copyright claims, and even if the state chooses to use copyright claims as cover for your persecution, that's just window dressing.
