### ISSUE TITLE
The "within thirty days"

### ISSUE THREAD

**Issue by tunnckoCore** [licensezero/parity-public-license#71]
Let's say you use something licensed under this unknowingly for 29-30 days, then you realized that you are violating this license. So you have more 30 days from the Excuse clause.

That makes 2 months I think the thought is to have 30 days trails, strictly. So, did you had this in mind or it's just a mistake? Or it's just me how I hearing and understanding it.

Btw side note, any plans when will update the `Prosperity` to this template?

**Comment by kemitchell** [comment]
@tunnckoCore Parity _does_ intend to provide a grace period. Users shouldn't be able to ignore the license, or avoid learning about it, and then get away with violations. But users who just plain don't find out about the terms---say because someone before them failed to follow Notices---should have a grace period. Hence the language in Excuse that ties the new thirty-day deadline to when the user learned they broke a rule.

As for the deadlines, I agree that two months could be too long. But I also think that just one month could be too short. A license can't get the deadlines perfectly right, but thirty days seems to strike most folks as fair and practical, most of the time. GPL and other licenses with grace periods give similar deadlines.

**Comment by tunnckoCore** [comment]
Thanks. :)
