### ISSUE TITLE
Re-Licensing to later versions of parity

### ISSUE THREAD

**Issue by Iolaum** [licensezero/parity-public-license#74]
I was wondering whether a behavior similar to "GPLv2 or later" is allowed under parity license. I think the relevant test is from parity v7, Contribute, point2:

> Make sure every part of the source code is available under this license or another license that allows everything this license does, 

Let's say that some years down the line someone finds software licensed with parity v7. Does that allow them to modify it and publish changes in (for example) parity v10?

**Comment by kemitchell** [comment]
> Let's say that some years down the line someone finds software licensed with parity v7. Does that allow them to modify it and publish changes in (for example) parity v10?

That would depend on what Parity 10 says.  Which of course we don't know yet. ;-P

The problem of field-upgradable license terms is a very real one, and I'm glad you brought it up.  In general, projects with contributions from people who aren't all working for the same company can't change the license terms for their project as a whole without getting every contributor's agreement to do so.

FSF's `GPL-2.0-or-later` is an attempt to solve that problem, but not one I like. I don't think anyone---foundation, business, or individual---should be asking for that kind of trust, especially without a lot of thorough explanation of what it entails.

I've been working on a better solution, [cross-license collaboratives](https://xlcollaborative.com/). In a nutshell, it works like a CLA, but instead of contributors giving special license powers to a company or foundation, they give those powers to each other.  The whole can then vote, coop style, to offer new or different license terms in the future, by majority vote of those responding, rather than the unanimous approval of everyone who's ever contributed.

**Comment by kemitchell** [comment]
To cap this off, I think it's perfectly possible to say something like "Parity Public License Version 7.0.0, or any later version published on paritylicense.com". But I'd encourage project leaders to instead consider getting permission from contributors to change the license terms for their contributions in the future, such as through a contributor license agreement.

The only effective "governance process" over publication of new Parity versions right now is my SSH key for the Web server. And given the kind of license Parity is and the differing reasons it's appealing to different projects, I probably wouldn't recommend delegating "upgrades" to a foundation stewarding it, even if their whole process was set out in a published set of bylaws.
