### ISSUE TITLE
OSI approval for parity license?

### ISSUE THREAD

**Issue by Iolaum** [licensezero/parity-public-license#77]
Hello,

I have started using the parity license for a side project of mine, [podcust](https://github.com/Iolaum/podcust) and I have one question regarding OSI approved licenses.

At the moment the license doesn't appeared to be included in the [approved OSI licenses](https://opensource.org/licenses/alphabetical). Is there any intend to remedy that? I am assuming that the license complied with the OSI definition, please correct me if I am wrong.

The reason I am asking is that OSI approval is standard that is acceptable by other people. Otherwise contributors or outside stajeholders will likely have to do their own ad-hoc assessment which will require more resources.

I don't know how hard such a request is, or how long it could take. I don't wish to put any undue burden on the people involved with parity public license.

**Comment by kemitchell** [comment]
The Parity Public License descends from a license originally called the "License Zero Reciprocal Public License". That was also a "free for open source" license. I submitted that older license to OSI way back when. It went terribly, wasting a bunch of my time, and producing a whole ton of drama that continues, in various ways, today. It also thoroughly corrected my view of what actually happens in OSI license review, which was not much or at all what I thought.

I no longer care whether OSI approves a license or not. As it it turned out, neither did any of the folks I thought I was serving by taking the form to their process.

I personally have no interest in ever taking a license to OSI again. That includes even thoroughly uncontroversial licenses I've been involved in drafting, like the [Blue Oak Model License](https://blueoakcouncil.org/license/1.0.0). I wouldn't try to stop others from doing so. But I would try to make them aware of what they're getting into.

> The reason I am asking is that OSI approval is standard that is acceptable by other people. Otherwise contributors or outside stajeholders will likely have to do their own ad-hoc assessment which will require more resources.

Say we went and got OSI to approve Parity. Which big companies would whitelist Parity-licensed software on that basis, seeing as it requires sharing software alike?

As for contributors, I think it's easy enough to explain that Parity means "free for open source", and not closed or proprietary projects. You'll want to give some thought to how you handle licensing of contributions: whether you want the project "locked open", so even you have to follow Parity's rules, or you want to have the right to ignore the license, sell exceptions, and so on, like a company or foundation.

**Comment by Iolaum** [comment]
Thank you for your reply and detailed explanation! I appreciate it.
